DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS film CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS rating CASCADE;
DROP TABLE IF EXISTS film_like CASCADE;
DROP TABLE IF EXISTS friend_user CASCADE;
DROP TABLE IF EXISTS film_genre CASCADE;
DROP TABLE IF EXISTS film_rating;
CREATE TABLE users
(
    id_user    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      varchar(40) NOT NULL, --UNIQUE,
    login_user varchar(40) NOT NULL,
    name_user  varchar(40) ,
    birthday   date        NOT NULL
);

CREATE TABLE film
(
    id_film     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_film   varchar(40) NOT NULL,
    description varchar(200),
    release_date date,
    duration    int,
    rate integer NOT NULL

);

CREATE TABLE genre
(
    id_genre   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_genre varchar(40) NOT NULL
);

CREATE TABLE rating
(
    id_rating  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_rating varchar(40)
);

CREATE TABLE film_like
(
    id_film INTEGER REFERENCES film (id_film),
    id_user INTEGER REFERENCES users (id_user)
);

CREATE TABLE friend_user
(
    id_user       INTEGER REFERENCES users (id_user),
    id_friend     INTEGER REFERENCES users (id_user),

    status_friend int
);

CREATE TABLE film_genre
(
    id_film  INTEGER REFERENCES film (id_film),
    id_genre INTEGER REFERENCES genre (id_genre)
);

CREATE TABLE film_rating
(
    id_film  INTEGER REFERENCES film (id_film),
    id_rating INTEGER REFERENCES rating (id_rating)
);

INSERT INTO genre (name_genre) VALUES ( 'Комедия' );
INSERT INTO genre (name_genre) VALUES ( 'Драма' );
INSERT INTO genre (name_genre) VALUES ( 'Мультфильм' );
INSERT INTO genre (name_genre) VALUES ( 'Триллер' );
INSERT INTO genre (name_genre) VALUES ( 'Документальный' );
INSERT INTO genre (name_genre) VALUES ( 'Боевик' );

INSERT INTO rating (name_rating) VALUES ('G');
INSERT INTO rating (name_rating) VALUES ('PG');
INSERT INTO rating (name_rating) VALUES ('PG-13');
INSERT INTO rating (name_rating) VALUES ('R' );
INSERT INTO rating (name_rating) VALUES ('NC-17');

